{{- if .Values.valkey.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "synapse.fullname" . }}-valkey
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.valkey.port }}
      targetPort: valkey
      protocol: TCP
      name: valkey
  selector:
    {{- include "synapse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
{{- end }}
